import { useRef } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import Image from 'next/image'
import Avatar from '../components/Avatar'
import { ViewGridIcon, MicrophoneIcon } from '@heroicons/react/solid'
import { SearchIcon } from '@heroicons/react/outline'
import Footer from '../components/Footer'

export default function Home() {

  const searchRef = useRef()
  const router = useRouter()

  const search = e => {
    e.preventDefault()
    const term = searchRef.current.value
    if (!term) return
    router.push(`/search?term=${term}`)
  }

  return (
    <div className='flex flex-col items-center justify-content h-screen'>
      <Head>
        <title>Serch Platform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className='flex justify-between w-full p-5 text-sm text-gray-700'>
        <div className='flex space-x-4 items-center'>
          <p className='link'>About</p>
          <p className='link'>Store</p>
        </div>
        <div className='flex space-x-4 items-center'>
          <p className='link'>Gmail</p>
          <p className='link'>Picture</p>
          <ViewGridIcon className='h-10 w-10 p-2 cursor-pointer rounded-full transition duration-200 hover:bg-gray-100' />
          <div className='transform hover:scale-110  transition duration-200'><Avatar url='https://wiki.teamfortress.com/w/images/thumb/b/bc/Icon_engineer.jpg/150px-Icon_engineer.jpg' /></div>
        </div>
      </header>
      <form className='flex flex-col items-center mt-44 flex-grow w-4/5'>
        <Image
          src='https://storage.googleapis.com/gd-wagtail-prod-assets/original_images/evolving_google_identity_inline_005.jpg'
          width={500}
          height={250}
          alt='logo'
        />
        <div className='flex w-full justify-center hover:shadow-lg 
        focus-within:shadow-lg max-w-md rounded-full 
        border border-gray-200 px-5 py-3 items-center sm:max-w-xl 
        lg:max-w-2xl transition duration-200'>
          <SearchIcon className='h-5 mr-3 text-gray-500 ' />
          <input ref={searchRef} type='text' className='focus:outline-none flex-grow ' />
          <MicrophoneIcon className='h-5 mr-3 text-gray-500 ' />
        </div>
        <div className='flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:flex-row sm:space-y-0 sm:space-x-2 '>
          <button onClick={search} className='btn'>Google Search</button>
          <button onClick={search} className='btn'>Lucky Strike</button>
        </div>
      </form>
      <Footer />
    </div>
  )
}
